import {
	defineAdapter,
	INJECT_TAGS_SOURCE,
	missingDocumentMessage,
	type AdapterEntryContext,
} from '@riproute/adapter-kit';

/**
 * The Cloudflare Workers target's build-time half.
 *
 * A Worker is uploaded as one self-contained module, which drives both
 * differences from the server targets: `noExternal` (there is no
 * `node_modules` to resolve a bare import against at runtime) and a template
 * baked in as a string (there is no filesystem to read one from).
 */
export default defineAdapter({
	name: 'cloudflare',
	runtimePackage: '@riproute/cloudflare',
	startHint: 'wrangler deploy',

	viteConfig: { noExternal: true },

	entry(context: AdapterEntryContext): string {
		return [
			'// Generated by riproute.',
			"import { createFetchHandler } from '@riproute/cloudflare';",
			`import { createRiprouteHandler, shell } from ${JSON.stringify(context.handlerId)};`,
			'',
			`const tags = ${JSON.stringify(context.tags)};`,
			// Baked, not read: a Worker has no filesystem.
			`const template = ${JSON.stringify(context.template)};`,
			'',
			'if (shell === undefined && template === null) {',
			`\tthrow new Error(${JSON.stringify(missingDocumentMessage(context.templatePath))});`,
			'}',
			'',
			INJECT_TAGS_SOURCE,
			'',
			'const handler = createRiprouteHandler({',
			'\ttemplate: shell === undefined ? template : undefined,',
			'\ttransformTemplate: (html) => injectTags(html),',
			'});',
			'',
			'export default { fetch: createFetchHandler(handler) };',
		].join('\n');
	},
});
