import path from 'node:path';

import type { DiscoveredRoutes } from './route-scan';
import type { ResolvedRiprouteOptions } from './options';

export const ROUTES_ID = 'virtual:riproute/routes';
export const CLIENT_ID = 'virtual:riproute/client';
export const HANDLER_ID = 'virtual:riproute/handler';
export const SERVER_ID = 'virtual:riproute/server';

export const VIRTUAL_IDS = [ROUTES_ID, CLIENT_ID, HANDLER_ID, SERVER_ID] as const;

/** Vite's convention: a `\0` prefix keeps other plugins from touching the id. */
export function resolvedId(id: string): string {
	return `\0${id}`;
}

/** The browser URL for a virtual module during dev. */
export function devUrl(id: string): string {
	return `/@id/__x00__${id}`;
}

/**
 * Rewrites an absolute path into an import specifier Vite can resolve.
 *
 * Root-relative wherever possible. That is not cosmetic: Rollup derives chunk
 * names from entry specifiers during the client build and rejects anything
 * that is not root-relative with `Invalid substitution ... for placeholder
 * "[name]"`.
 */
export function toImportSpecifier(file: string, root: string): string {
	const relative = path.relative(root, file);

	if (relative.startsWith('..') || path.isAbsolute(relative)) {
		return `/@fs/${file.split(path.sep).join('/')}`;
	}

	return `/${relative.split(path.sep).join('/')}`;
}

/**
 * The generated route table.
 *
 * Namespace imports rather than default imports, so a route file that forgets
 * its `export default` fails with a message naming the file instead of
 * rendering `undefined`.
 */
export function generateRoutesModule(
	discovered: DiscoveredRoutes,
	options: ResolvedRiprouteOptions,
	root: string
): string {
	const lines: string[] = [];
	const entries: string[] = [];

	lines.push(
		'// Generated by riproute. Edit files in your routes directory instead.',
		'function pick(module, file) {',
		'\tconst element = module.default;',
		'',
		'\tif (typeof element !== "function") {',
		'\t\tthrow new Error(`[riproute] ${file} must "export default" a component.`);',
		'\t}',
		'',
		'\treturn element;',
		'}',
		''
	);

	discovered.routes.forEach((route, index) => {
		const specifier = toImportSpecifier(route.file, root);

		lines.push(`import * as route${index} from ${JSON.stringify(specifier)};`);
		entries.push(
			`\t{ path: ${JSON.stringify(route.path)}, element: pick(route${index}, ${JSON.stringify(
				specifier
			)}) },`
		);
	});

	if (discovered.root !== null) {
		const specifier = toImportSpecifier(discovered.root, root);

		lines.push(`import * as rootRoute from ${JSON.stringify(specifier)};`);
		lines.push('', `export const root = pick(rootRoute, ${JSON.stringify(specifier)});`);
	} else {
		lines.push('', 'export const root = undefined;');
	}

	lines.push('', 'export const routes = [', ...entries, '];');
	lines.push(
		'',
		`export const config = ${JSON.stringify({
			base: options.base,
			title: options.title,
			rootId: options.rootId,
		})};`
	);

	return lines.join('\n');
}

/** Re-exports a hand-written route table so both modes look the same downstream. */
export function generateRoutesProxyModule(
	routesModule: string,
	options: ResolvedRiprouteOptions,
	root: string
): string {
	const specifier = toImportSpecifier(routesModule, root);

	return [
		'// Generated by riproute.',
		`import * as source from ${JSON.stringify(specifier)};`,
		'',
		'export const routes = source.routes ?? source.default;',
		'export const root = source.root;',
		'',
		'if (!Array.isArray(routes)) {',
		`\tthrow new Error('[riproute] ${JSON.stringify(specifier).slice(1, -1)} must export a "routes" array.');`,
		'}',
		'',
		`export const config = ${JSON.stringify({
			base: options.base,
			title: options.title,
			rootId: options.rootId,
		})};`,
	].join('\n');
}

/**
 * The hydration entry.
 *
 * It hydrates the same `createRouterApp()` wrapper the server rendered — an
 * extra component on one side only would shift the hydration cursor and drop
 * the whole tree back to a client mount.
 */
export function generateClientModule(): string {
	return [
		'// Generated by riproute.',
		"import { hydrate } from 'ripple';",
		"import { createRouterApp } from 'riproute';",
		`import { config, root, routes } from ${JSON.stringify(ROUTES_ID)};`,
		'',
		'const target = document.getElementById(config.rootId);',
		'',
		'if (target === null) {',
		'\tthrow new Error(`[riproute] No #${config.rootId} element to hydrate into.`);',
		'}',
		'',
		'hydrate(',
		'\tcreateRouterApp({ routes, root, base: config.base, title: config.title }),',
		'\t{ target }',
		');',
	].join('\n');
}

/** The handler factory, shared by the dev middleware and the production entry. */
export function generateHandlerModule(): string {
	return [
		'// Generated by riproute.',
		"import { createHandler } from 'riproute/server';",
		`import { config, root, routes } from ${JSON.stringify(ROUTES_ID)};`,
		'',
		'export { config, root, routes };',
		'',
		'export function createRiprouteHandler(options) {',
		'\treturn createHandler({',
		'\t\troutes,',
		'\t\troot,',
		'\t\tbase: config.base,',
		'\t\ttitle: config.title,',
		'\t\trootId: config.rootId,',
		'\t\t...options,',
		'\t});',
		'}',
	].join('\n');
}

/**
 * The production entry: a complete server, not a snippet to wire up.
 *
 * `dist/server/index.js` reads the built shell out of the sibling client
 * directory, so `node dist/server` serves the app with nothing else on disk.
 */
export function generateServerModule(options: ResolvedRiprouteOptions): string {
	return [
		'// Generated by riproute.',
		"import fs from 'node:fs';",
		"import path from 'node:path';",
		"import { fileURLToPath } from 'node:url';",
		"import { createServer, serveStatic } from 'riproute/adapter-node';",
		`import { createRiprouteHandler } from ${JSON.stringify(HANDLER_ID)};`,
		'',
		'const here = path.dirname(fileURLToPath(import.meta.url));',
		`const clientDir = path.resolve(here, ${JSON.stringify(options.clientDirFromServer)});`,
		"const template = fs.readFileSync(path.join(clientDir, 'index.html'), 'utf-8');",
		'',
		`const assets = serveStatic(clientDir, { immutable: [${JSON.stringify(
			options.assetsDir
		)}] });`,
		'',
		'export const handler = createRiprouteHandler({ template, onRequest: assets });',
		'',
		'export const server = createServer(handler);',
		'',
		'export function start(options) {',
		'\treturn server.listen(options);',
		'}',
		'',
		'// Booting on import keeps `node dist/server` working;',
		'// importing the module for its `handler` sets RIPROUTE_NO_LISTEN.',
		"if (process.env.RIPROUTE_NO_LISTEN !== '1') {",
		'\tstart({ port: Number(process.env.PORT ?? 3000), host: process.env.HOST });',
		'}',
	].join('\n');
}
