import path from 'node:path';

import type { DiscoveredRoutes } from './route-scan';
import type { ResolvedRiprouteOptions } from './options';

export const ROUTES_ID = 'virtual:riproute/routes';
export const CLIENT_ID = 'virtual:riproute/client';
export const HANDLER_ID = 'virtual:riproute/handler';
export const SERVER_ID = 'virtual:riproute/server';

export const VIRTUAL_IDS = [ROUTES_ID, CLIENT_ID, HANDLER_ID, SERVER_ID] as const;

/** Vite's convention: a `\0` prefix keeps other plugins from touching the id. */
export function resolvedId(id: string): string {
	return `\0${id}`;
}

/** The browser URL for a virtual module during dev. */
export function devUrl(id: string): string {
	return `/@id/__x00__${id}`;
}

/**
 * Rewrites an absolute path into an import specifier Vite can resolve.
 *
 * Root-relative wherever possible. That is not cosmetic: Rollup derives chunk
 * names from entry specifiers during the client build and rejects anything
 * that is not root-relative with `Invalid substitution ... for placeholder
 * "[name]"`.
 */
export function toImportSpecifier(file: string, root: string): string {
	const relative = path.relative(root, file);

	if (relative.startsWith('..') || path.isAbsolute(relative)) {
		return `/@fs/${file.split(path.sep).join('/')}`;
	}

	return `/${relative.split(path.sep).join('/')}`;
}

/**
 * The generated route table.
 *
 * Namespace imports rather than default imports, so a route file that forgets
 * its `export default` fails with a message naming the file instead of
 * rendering `undefined`.
 */
export function generateRoutesModule(
	discovered: DiscoveredRoutes,
	options: ResolvedRiprouteOptions,
	root: string,
	baseTitle: string | null
): string {
	const lines: string[] = [];
	const entries: string[] = [];

	lines.push(
		'// Generated by riproute. Edit files in your routes directory instead.',
		'function pick(module, file) {',
		'\tconst element = module.default;',
		'',
		'\tif (typeof element !== "function") {',
		'\t\tthrow new Error(`[riproute] ${file} must "export default" a component.`);',
		'\t}',
		'',
		'\treturn element;',
		'}',
		''
	);

	discovered.routes.forEach((route, index) => {
		const specifier = toImportSpecifier(route.file, root);

		lines.push(`import * as route${index} from ${JSON.stringify(specifier)};`);
		entries.push(
			`\t{ path: ${JSON.stringify(route.path)}, element: pick(route${index}, ${JSON.stringify(
				specifier
			)}) },`
		);
	});

	if (discovered.root !== null) {
		const specifier = toImportSpecifier(discovered.root, root);

		lines.push(`import * as rootRoute from ${JSON.stringify(specifier)};`);
		lines.push('', `export const root = pick(rootRoute, ${JSON.stringify(specifier)});`);
		// The document shell, if the root route exports one. Named rather than
		// default so a root route can own the document *and* be a layout.
		lines.push('export const shell = rootRoute.shell;');
	} else {
		lines.push('', 'export const root = undefined;', 'export const shell = undefined;');
	}

	lines.push('', 'export const routes = [', ...entries, '];');
	lines.push('', `export const config = ${JSON.stringify(configOf(options, baseTitle))};`);

	return lines.join('\n');
}

/** Re-exports a hand-written route table so both modes look the same downstream. */
export function generateRoutesProxyModule(
	routesModule: string,
	options: ResolvedRiprouteOptions,
	root: string,
	baseTitle: string | null
): string {
	const specifier = toImportSpecifier(routesModule, root);

	return [
		'// Generated by riproute.',
		`import * as source from ${JSON.stringify(specifier)};`,
		'',
		'export const routes = source.routes ?? source.default;',
		'export const root = source.root;',
		'export const shell = source.shell;',
		'',
		'if (!Array.isArray(routes)) {',
		`\tthrow new Error('[riproute] ${JSON.stringify(specifier).slice(1, -1)} must export a "routes" array.');`,
		'}',
		'',
		`export const config = ${JSON.stringify(configOf(options, baseTitle))};`,
	].join('\n');
}

/**
 * The bits of the resolved options both entries need at runtime.
 *
 * A `<title>` in the root route's `<head>` wins over the plugin's `title`
 * option: it is where the document's own title belongs, and repeating it in
 * `vite.config.ts` is the kind of duplication that goes stale.
 */
function configOf(options: ResolvedRiprouteOptions, baseTitle: string | null) {
	return {
		base: options.base,
		title: baseTitle ?? options.title,
		rootId: options.rootId,
	};
}

/**
 * The hydration entry.
 *
 * It hydrates the same `createRouterApp()` wrapper the server rendered — an
 * extra component on one side only would shift the hydration cursor and drop
 * the whole tree back to a client mount.
 */
export function generateClientModule(): string {
	return [
		'// Generated by riproute.',
		"import { hydrate } from 'ripple';",
		"import { createRouterApp } from 'riproute';",
		`import { config, root, routes } from ${JSON.stringify(ROUTES_ID)};`,
		'',
		// An app with an index.html mounts into its #root element; one whose
		// root route renders the document has no mount div at all — the app
		// sits directly in <body>, and hydration finds its own markers there.
		'const target = document.getElementById(config.rootId) ?? document.body;',
		'',
		'hydrate(',
		'\tcreateRouterApp({ routes, root, base: config.base, title: config.title }),',
		'\t{ target }',
		');',
	].join('\n');
}

/**
 * The handler factory, shared by the dev middleware and the production entry.
 *
 * Both go through here so the app's hooks behave identically in dev and in
 * production — a JSON endpoint that only exists in one of them is worse than no
 * endpoint at all.
 */
export function generateHandlerModule(options: ResolvedRiprouteOptions, root: string): string {
	const hooks = options.hooksModule;
	const lines = [
		'// Generated by riproute.',
		"import { createHandler } from 'riproute/server';",
		`import { config, root, routes, shell } from ${JSON.stringify(ROUTES_ID)};`,
	];

	if (hooks !== null) {
		lines.push(`import * as hooks from ${JSON.stringify(toImportSpecifier(hooks, root))};`);
	}

	lines.push(
		'',
		'export { config, root, routes, shell };',
		'',
		'export function createRiprouteHandler(options = {}) {',
		// Static assets come in as `options.onRequest` from the production
		// entry. They run first: cheap, specific, and it keeps every image
		// request from walking through the app's hooks.
		`\tconst before = [options.onRequest${hooks === null ? '' : ', hooks.onRequest'}].filter(`,
		'\t\t(hook) => typeof hook === "function"',
		'\t);',
		'',
		'\treturn createHandler({',
		'\t\troutes,',
		'\t\troot,',
		'\t\tbase: config.base,',
		'\t\ttitle: config.title,',
		'\t\trootId: config.rootId,',
		'\t\tshell,',
		'\t\t...options,',
		'\t\tonRequest:',
		'\t\t\tbefore.length === 0',
		'\t\t\t\t? undefined',
		'\t\t\t\t: async (request) => {',
		'\t\t\t\t\t\tfor (const hook of before) {',
		'\t\t\t\t\t\t\tconst response = await hook(request);',
		'',
		'\t\t\t\t\t\t\tif (response !== undefined) return response;',
		'\t\t\t\t\t\t}',
		'\t\t\t\t\t},',
		`\t\tonError: options.onError${hooks === null ? '' : ' ?? hooks.onError'},`,
		'\t});',
		'}'
	);

	return lines.join('\n');
}

/**
 * The production entry: a complete server, not a snippet to wire up.
 *
 * `dist/server/index.js` reads the built shell out of the sibling client
 * directory, so `node dist/server` serves the app with nothing else on disk.
 */
export function generateServerModule(options: ResolvedRiprouteOptions, tags: string): string {
	return [
		'// Generated by riproute.',
		"import fs from 'node:fs';",
		"import path from 'node:path';",
		"import { fileURLToPath } from 'node:url';",
		"import { createServer, serveStatic } from 'riproute/adapter-node';",
		`import { createRiprouteHandler, shell } from ${JSON.stringify(HANDLER_ID)};`,
		'',
		'const here = path.dirname(fileURLToPath(import.meta.url));',
		`const clientDir = path.resolve(here, ${JSON.stringify(options.clientDirFromServer)});`,
		'',
		'// A shell renders the document itself, so there is no index.html to read',
		'// — but it cannot know its own hashed asset names, so they are injected.',
		`const tags = ${JSON.stringify(tags)};`,
		'',
		'const template =',
		'\tshell === undefined',
		"\t\t? fs.readFileSync(path.join(clientDir, 'index.html'), 'utf-8')",
		'\t\t: undefined;',
		'',
		`const assets = serveStatic(clientDir, { immutable: [${JSON.stringify(options.assetsDir)}] });`,
		'',
		'export const handler = createRiprouteHandler({',
		'\ttemplate,',
		'\tonRequest: assets,',
		'\ttransformTemplate:',
		'\t\tshell === undefined',
		'\t\t\t? undefined',
		"\t\t\t: (html) => html.replace('</head>', `${tags}</head>`),",
		'});',
		'',
		'export const server = createServer(handler);',
		'',
		'export function start(options) {',
		'\treturn server.listen(options);',
		'}',
		'',
		'// Booting on import keeps `node dist/server` working;',
		'// importing the module for its `handler` sets RIPROUTE_NO_LISTEN.',
		"if (process.env.RIPROUTE_NO_LISTEN !== '1') {",
		'\tstart({ port: Number(process.env.PORT ?? 3000), host: process.env.HOST });',
		'}',
	].join('\n');
}
