import path from 'node:path';

import type { DiscoveredRoutes } from './route-scan';
import type { ResolvedRiprouteOptions } from './options';
import { collectServerFnExportsFromFile, serverFnHash } from './server-fn';

export const ROUTES_ID = 'virtual:riproute/routes';
export const CLIENT_ID = 'virtual:riproute/client';
export const HANDLER_ID = 'virtual:riproute/handler';
export const SERVER_ID = 'virtual:riproute/server';
export const NITRO_ID = 'virtual:riproute/nitro';
export const SERVER_FNS_ID = 'virtual:riproute/server-fns';

export const VIRTUAL_IDS = [
	ROUTES_ID,
	CLIENT_ID,
	HANDLER_ID,
	SERVER_ID,
	NITRO_ID,
	SERVER_FNS_ID,
] as const;

/** The dev-only endpoint the nitro entry reads CSS module ids from. */
export const DEV_CSS_IDS_PATH = '/__riproute/dev-css-ids';

/** Vite's convention: a `\0` prefix keeps other plugins from touching the id. */
export function resolvedId(id: string): string {
	return `\0${id}`;
}

/** The browser URL for a virtual module during dev. */
export function devUrl(id: string): string {
	return `/@id/__x00__${id}`;
}

/**
 * Rewrites an absolute path into an import specifier Vite can resolve.
 *
 * Root-relative wherever possible. That is not cosmetic: Rollup derives chunk
 * names from entry specifiers during the client build and rejects anything
 * that is not root-relative with `Invalid substitution ... for placeholder
 * "[name]"`.
 */
export function toImportSpecifier(file: string, root: string): string {
	const relative = path.relative(root, file);

	if (relative.startsWith('..') || path.isAbsolute(relative)) {
		return `/@fs/${file.split(path.sep).join('/')}`;
	}

	return `/${relative.split(path.sep).join('/')}`;
}

/**
 * The generated route table.
 *
 * Namespace imports rather than default imports, so a route file that forgets
 * its `export default` fails with a message naming the file instead of
 * rendering `undefined`.
 */
export function generateRoutesModule(
	discovered: DiscoveredRoutes,
	options: ResolvedRiprouteOptions,
	root: string,
	baseTitle: string | null
): string {
	const lines: string[] = [];
	const entries: string[] = [];

	lines.push(
		'// Generated by riproute. Edit files in your routes directory instead.',
		'function pick(module, file) {',
		'\tconst element = module.default;',
		'',
		'\tif (typeof element !== "function") {',
		'\t\tthrow new Error(`[riproute] ${file} must "export default" a component.`);',
		'\t}',
		'',
		'\treturn element;',
		'}',
		''
	);

	discovered.routes.forEach((route, index) => {
		const specifier = toImportSpecifier(route.file, root);

		lines.push(`import * as route${index} from ${JSON.stringify(specifier)};`);
		entries.push(
			`\t{ path: ${JSON.stringify(route.path)}, element: pick(route${index}, ${JSON.stringify(
				specifier
			)}) },`
		);
	});

	if (discovered.root !== null) {
		const specifier = toImportSpecifier(discovered.root, root);

		lines.push(`import * as rootRoute from ${JSON.stringify(specifier)};`);
		lines.push('', `export const root = pick(rootRoute, ${JSON.stringify(specifier)});`);
		// The document shell, if the root route exports one. Named rather than
		// default so a root route can own the document *and* be a layout.
		lines.push('export const shell = rootRoute.shell;');
	} else {
		lines.push('', 'export const root = undefined;', 'export const shell = undefined;');
	}

	lines.push('', 'export const routes = [', ...entries, '];');
	lines.push('', `export const config = ${JSON.stringify(configOf(options, baseTitle))};`);

	return lines.join('\n');
}

/** Re-exports a hand-written route table so both modes look the same downstream. */
export function generateRoutesProxyModule(
	routesModule: string,
	options: ResolvedRiprouteOptions,
	root: string,
	baseTitle: string | null
): string {
	const specifier = toImportSpecifier(routesModule, root);

	return [
		'// Generated by riproute.',
		`import * as source from ${JSON.stringify(specifier)};`,
		'',
		'export const routes = source.routes ?? source.default;',
		'export const root = source.root;',
		'export const shell = source.shell;',
		'',
		'if (!Array.isArray(routes)) {',
		`\tthrow new Error('[riproute] ${JSON.stringify(specifier).slice(1, -1)} must export a "routes" array.');`,
		'}',
		'',
		`export const config = ${JSON.stringify(configOf(options, baseTitle))};`,
	].join('\n');
}

/**
 * The bits of the resolved options both entries need at runtime.
 *
 * A `<title>` in the root route's `<head>` wins over the plugin's `title`
 * option: it is where the document's own title belongs, and repeating it in
 * `vite.config.ts` is the kind of duplication that goes stale.
 */
function configOf(options: ResolvedRiprouteOptions, baseTitle: string | null) {
	return {
		base: options.base,
		title: baseTitle ?? options.title,
		rootId: options.rootId,
	};
}

/**
 * The hydration entry.
 *
 * It hydrates the same `createRouterApp()` wrapper the server rendered — an
 * extra component on one side only would shift the hydration cursor and drop
 * the whole tree back to a client mount.
 */
export function generateClientModule(): string {
	return [
		'// Generated by riproute.',
		"import { hydrate } from 'ripple';",
		"import { createRouterApp } from '@riproute/router';",
		`import { config, root, routes } from ${JSON.stringify(ROUTES_ID)};`,
		'',
		// An app with an index.html mounts into its #root element; one whose
		// root route renders the document has no mount div at all — the app
		// sits directly in <body>, and hydration finds its own markers there.
		'const target = document.getElementById(config.rootId) ?? document.body;',
		'',
		'hydrate(',
		'\tcreateRouterApp({ routes, root, base: config.base, title: config.title }),',
		'\t{ target }',
		');',
	].join('\n');
}

/**
 * The server-function table: endpoint hash → export name + lazy module import.
 *
 * Lazy so a build with fifty `.server.ts` files pays for the ones a request
 * actually calls, and so a module-level crash in one cannot take the whole
 * server down at boot. The hashes are the same ones baked into the client
 * stubs — both sides derive them from the file's root-relative path and the
 * export name.
 */
export async function generateServerFnManifestModule(
	files: readonly string[],
	root: string
): Promise<string> {
	const entries: string[] = [];

	for (const file of files) {
		const specifier = JSON.stringify(toImportSpecifier(file, root));

		for (const name of await collectServerFnExportsFromFile(file)) {
			entries.push(
				`\t[${JSON.stringify(serverFnHash(file, root, name))}]: ` +
					`{ name: ${JSON.stringify(name)}, load: () => import(${specifier}) },`
			);
		}
	}

	return ['// Generated by riproute.', 'export const functions = {', ...entries, '};'].join('\n');
}

/**
 * The handler factory, shared by the dev middleware and the production entry.
 *
 * Both go through here so the app's hooks behave identically in dev and in
 * production — a JSON endpoint that only exists in one of them is worse than no
 * endpoint at all.
 */
export function generateHandlerModule(options: ResolvedRiprouteOptions, root: string): string {
	const hooks = options.hooksModule;
	const lines = [
		'// Generated by riproute.',
		"import { createHandler, createServerFnDispatch } from '@riproute/riproute/server';",
		`import { config, root, routes, shell } from ${JSON.stringify(ROUTES_ID)};`,
		`import { functions } from ${JSON.stringify(SERVER_FNS_ID)};`,
	];

	if (hooks !== null) {
		lines.push(`import * as hooks from ${JSON.stringify(toImportSpecifier(hooks, root))};`);
	}

	lines.push(
		'',
		'export { config, root, routes, shell };',
		'',
		'const serverFns = createServerFnDispatch(functions);',
		'',
		'export function createRiprouteHandler(options = {}) {',
		// Static assets come in as `options.onRequest` from the production
		// entry. They run first: cheap, specific, and it keeps every image
		// request from walking through the app's hooks. The app's hooks run
		// before the server-function dispatch, so an auth gate covers RPC
		// calls the same as pages.
		`\tconst before = [options.onRequest${hooks === null ? '' : ', hooks.onRequest'}, serverFns].filter(`,
		'\t\t(hook) => typeof hook === "function"',
		'\t);',
		'',
		'\treturn createHandler({',
		'\t\troutes,',
		'\t\troot,',
		'\t\tbase: config.base,',
		'\t\ttitle: config.title,',
		'\t\trootId: config.rootId,',
		'\t\tshell,',
		'\t\t...options,',
		'\t\tonRequest:',
		'\t\t\tbefore.length === 0',
		'\t\t\t\t? undefined',
		'\t\t\t\t: async (request) => {',
		'\t\t\t\t\t\tfor (const hook of before) {',
		'\t\t\t\t\t\t\tconst response = await hook(request);',
		'',
		'\t\t\t\t\t\t\tif (response !== undefined) return response;',
		'\t\t\t\t\t\t}',
		'\t\t\t\t\t},',
		`\t\tonError: options.onError${hooks === null ? '' : ' ?? hooks.onError'},`,
		'\t});',
		'}'
	);

	return lines.join('\n');
}

/**
 * The nitro service entry: `export default { fetch }`, which is the one shape
 * nitro's env-runner accepts, in dev and in production alike.
 *
 * Everything the `node:http` entry does around the handler falls away here.
 * Static assets, compression, ports and shutdown are nitro's job; what remains
 * is the riproute handler and the document it needs.
 */
export function generateNitroModule(
	options: ResolvedRiprouteOptions,
	args: {
		dev: boolean;
		/** Resolved Vite base, always with a trailing slash. */
		base: string;
		/** Built asset tags, empty during dev. */
		tags: string;
		/** Raw `index.html` content for template-mode apps, baked at build time. */
		template: string | null;
	}
): string {
	return args.dev ? nitroDevModule(options, args.base) : nitroProdModule(options, args);
}

/**
 * Dev: the entry runs inside nitro's environment runner, a Vite module runner
 * in a worker — the dev server itself is out of reach. The two things the dev
 * middleware would have done are recovered differently:
 *
 * - Vite's client and the hydration entry are fixed URLs, injected directly.
 * - CSS inlining (the anti-FOUC measure) needs the server-side module graph,
 *   so riproute keeps a tiny endpoint that lists the CSS module ids; the
 *   entry imports each through the runner as `?inline` and inlines the text.
 */
function nitroDevModule(options: ResolvedRiprouteOptions, base: string): string {
	const devScripts =
		`<script type="module" src="${base}@vite/client"></script>` +
		`<script type="module" src="${base}@id/__x00__${CLIENT_ID}"></script>`;

	return [
		'// Generated by riproute.',
		`import { createRiprouteHandler, shell } from ${JSON.stringify(HANDLER_ID)};`,
		'',
		`const DEV_SCRIPTS = ${JSON.stringify(devScripts)};`,
		'',
		'async function devCss(request) {',
		'\tlet ids = [];',
		'',
		'\ttry {',
		`\t\tconst response = await fetch(new URL(${JSON.stringify(DEV_CSS_IDS_PATH)}, request.url));`,
		'',
		'\t\tif (response.ok) ids = await response.json();',
		'\t} catch {',
		'\t\t// The endpoint lives on the dev server; without it styles still',
		'\t\t// arrive through the client entry, just after first paint.',
		'\t}',
		'',
		"\tlet out = '';",
		'',
		'\tfor (const id of ids) {',
		'\t\ttry {',
		'\t\t\tconst mod = await import(',
		'\t\t\t\t/* @vite-ignore */',
		"\t\t\t\tid.includes('?') ? id.replace('?', '?inline&') : `${id}?inline`",
		'\t\t\t);',
		'',
		"\t\t\tif (typeof mod.default === 'string' && mod.default !== '') {",
		'\t\t\t\tout += `<style data-riproute-dev-css=${JSON.stringify(id)}>${mod.default}</style>`;',
		'\t\t\t}',
		'\t\t} catch {',
		'\t\t\t// An id the runner cannot inline; the JS-injected copy still applies.',
		'\t\t}',
		'\t}',
		'',
		'\treturn out;',
		'}',
		'',
		'const handler = createRiprouteHandler({',
		'\ttemplate:',
		'\t\tshell === undefined',
		'\t\t\t? async () =>',
		"\t\t\t\t\t(await import('node:fs/promises')).readFile(",
		`\t\t\t\t\t\t${JSON.stringify(options.template)},`,
		"\t\t\t\t\t\t'utf-8'",
		'\t\t\t\t\t)',
		'\t\t\t: undefined,',
		'\ttransformTemplate: async (html, request) => {',
		'\t\tconst extras = (await devCss(request)) + DEV_SCRIPTS;',
		'\t\tconst close = /<\\/head\\s*>/i.exec(html);',
		'',
		'\t\treturn close === null',
		'\t\t\t? extras + html',
		'\t\t\t: html.slice(0, close.index) + extras + html.slice(close.index);',
		'\t},',
		'});',
		'',
		'export default { fetch: (request) => handler(request) };',
	].join('\n');
}

/**
 * Production: the document is baked into the bundle. Template-mode apps get
 * their raw `index.html` inlined (never written into nitro's public directory,
 * where it would shadow the renderer); shell-mode apps render their own.
 * Either way the hashed asset tags from the client build are injected at
 * request time, exactly as the `node:http` entry does it.
 */
function nitroProdModule(
	options: ResolvedRiprouteOptions,
	args: { tags: string; template: string | null }
): string {
	const missing =
		'[riproute] No document to render: the root route exports no shell ' +
		`and no template was found at ${options.template}.`;

	return [
		'// Generated by riproute.',
		`import { createRiprouteHandler, shell } from ${JSON.stringify(HANDLER_ID)};`,
		'',
		`const tags = ${JSON.stringify(args.tags)};`,
		`const template = ${JSON.stringify(args.template)};`,
		'',
		'if (shell === undefined && template === null) {',
		`\tthrow new Error(${JSON.stringify(missing)});`,
		'}',
		'',
		'function injectTags(html) {',
		"\tif (tags === '') return html;",
		'',
		'\tconst close = /<\\/head\\s*>/i.exec(html);',
		'',
		'\treturn close === null',
		'\t\t? html + tags',
		'\t\t: html.slice(0, close.index) + tags + html.slice(close.index);',
		'}',
		'',
		'const handler = createRiprouteHandler({',
		'\ttemplate: shell === undefined ? template : undefined,',
		'\ttransformTemplate: (html) => injectTags(html),',
		'});',
		'',
		'export default { fetch: (request) => handler(request) };',
	].join('\n');
}
