import { defineAdapter, INJECT_TAGS_SOURCE, type AdapterEntryContext } from '@riproute/adapter-kit';

/**
 * The Node target's build-time half.
 *
 * Imported by the Vite plugin, never by the app. It produces a
 * `dist/server/index.js` that is a complete server: it reads the built shell
 * out of the sibling client directory, serves the hashed assets, and boots on
 * import so `node dist/server` is the whole deployment.
 */
export default defineAdapter({
	name: 'node',
	runtimePackage: '@riproute/node',
	startHint: 'node dist/server',

	entry(context: AdapterEntryContext): string {
		return [
			'// Generated by riproute.',
			"import fs from 'node:fs';",
			"import path from 'node:path';",
			"import { fileURLToPath } from 'node:url';",
			"import { createServer, serveStatic } from '@riproute/node';",
			`import { createRiprouteHandler, shell } from ${JSON.stringify(context.handlerId)};`,
			'',
			'const here = path.dirname(fileURLToPath(import.meta.url));',
			`const clientDir = path.resolve(here, ${JSON.stringify(context.clientDirFromServer)});`,
			'',
			'// A shell renders the document itself, so there is no index.html to read',
			'// — but it cannot know its own hashed asset names, so they are injected.',
			`const tags = ${JSON.stringify(context.tags)};`,
			'',
			INJECT_TAGS_SOURCE,
			'',
			'const template =',
			'\tshell === undefined',
			"\t\t? fs.readFileSync(path.join(clientDir, 'index.html'), 'utf-8')",
			'\t\t: undefined;',
			'',
			`const assets = serveStatic(clientDir, { immutable: [${JSON.stringify(
				context.assetsDir
			)}], base: ${JSON.stringify(context.base)} });`,
			'',
			'export const handler = createRiprouteHandler({',
			'\ttemplate,',
			'\tonRequest: assets,',
			'\ttransformTemplate: shell === undefined ? undefined : (html) => injectTags(html),',
			'});',
			'',
			'export const server = createServer(handler);',
			'',
			'export function start(options) {',
			'\treturn server.listen(options);',
			'}',
			'',
			'// Booting on import keeps `node dist/server` working;',
			'// importing the module for its `handler` sets RIPROUTE_NO_LISTEN.',
			"if (process.env.RIPROUTE_NO_LISTEN !== '1') {",
			'\tstart({ port: Number(process.env.PORT ?? 3000), host: process.env.HOST });',
			'}',
		].join('\n');
	},
});
