import { defineAdapter, INJECT_TAGS_SOURCE, type AdapterEntryContext } from '@riproute/adapter-kit';

/**
 * The Bun target's build-time half.
 *
 * The same complete server as the Node target — Bun speaks web standards, so
 * only the import and the runtime underneath it differ.
 */
export default defineAdapter({
	name: 'bun',
	runtimePackage: '@riproute/bun',
	startHint: 'bun dist/server',

	entry(context: AdapterEntryContext): string {
		return [
			'// Generated by riproute.',
			"import fs from 'node:fs';",
			"import path from 'node:path';",
			"import { fileURLToPath } from 'node:url';",
			"import { createServer, serveStatic } from '@riproute/bun';",
			`import { createRiprouteHandler, shell } from ${JSON.stringify(context.handlerId)};`,
			'',
			'const here = path.dirname(fileURLToPath(import.meta.url));',
			`const clientDir = path.resolve(here, ${JSON.stringify(context.clientDirFromServer)});`,
			'',
			`const tags = ${JSON.stringify(context.tags)};`,
			'',
			INJECT_TAGS_SOURCE,
			'',
			'const template =',
			'\tshell === undefined',
			"\t\t? fs.readFileSync(path.join(clientDir, 'index.html'), 'utf-8')",
			'\t\t: undefined;',
			'',
			`const assets = serveStatic(clientDir, { immutable: [${JSON.stringify(
				context.assetsDir
			)}], base: ${JSON.stringify(context.base)} });`,
			'',
			'export const handler = createRiprouteHandler({',
			'\ttemplate,',
			'\tonRequest: assets,',
			'\ttransformTemplate: shell === undefined ? undefined : (html) => injectTags(html),',
			'});',
			'',
			'export const server = createServer(handler);',
			'',
			'export function start(options) {',
			'\treturn server.listen(options);',
			'}',
			'',
			"if (process.env.RIPROUTE_NO_LISTEN !== '1') {",
			'\tstart({ port: Number(process.env.PORT ?? 3000), host: process.env.HOST });',
			'}',
		].join('\n');
	},
});
